import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c9ac',
        'primary-container': '#c3f400',
        'primary-fixed-dim': '#abd600',
        'on-primary-container': '#556d00',
        'on-primary': '#283500',
        'secondary-container': '#00e0ff',
        'on-secondary-container': '#005f6d',
        'on-secondary': '#00363f',
        'outline': '#8e9379',
        'outline-variant': '#444933',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'surface-variant': '#353534',
        'surface-tint': '#abd600',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'background': '#131313',
        'on-background': '#e5e2e1',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', fontWeight: '700' }],
        'data-lg': ['20px', { lineHeight: '1.2', fontWeight: '600' }],
        'data-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      fontFamily: {
        'display': ['Anton', 'sans-serif'],
        'display-lg': ['Anton'],
        'headline-lg': ['Anton'],
        'headline-md': ['Anton'],
        'body-lg': ['Lexend'],
        'body-md': ['Lexend'],
        'label-caps': ['Lexend'],
        'data-lg': ['JetBrains Mono'],
        'data-sm': ['JetBrains Mono'],
        'body': ['Lexend', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        sans: ['Lexend', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
export default config
